### CREATE New Feature
POST http://localhost:3000/features/
Content-Type: application/json

{
	"name": "Spell Casting",
	"description": "The Ability To Cast Spells"
}

### CREATE Feature With Missing Name
POST http://localhost:3000/features/
Content-Type: application/json

{
	"description": "The Ability To Cast Spells"
}

### CREATE Feature With Missing Description
POST http://localhost:3000/features/
Content-Type: application/json

{
	"name": "Spell Casting"
}

### FIND all features 
GET http://localhost:3000/features/

### FIND Feature by ID

GET http://localhost:3000/features/61afafb80e73d989360465a6

### FIND Feature By ID that doesn't exist

GET http://localhost:3000/features/61afafb80e73d989360465a5

### Update A Feature Description By ID

PATCH http://localhost:3000/features/61afafb80e73d989360465a6
Content-Type: application/json

{
	"description": "SPELL CASTING!!!"
}

### Update Feature Name By ID
PATCH http://localhost:3000/features/61afafb80e73d989360465a6
Content-Type: application/json

{
	"name": "SPELL CASTING!!!"
}

### DELETE a feature by ID
DELETE http://localhost:3000/features/61afafb80e73d989360465a6

